apiVersion: v1
kind: Pod
metadata:
  name: test-hostdev-pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: example-hostdevice-network
spec:
  nodeSelector:
    # Note: Replace hostname or remove selector altogether
    kubernetes.io/hostname: worker01
  containers:
    - name: test-hostdev-pod
      image: centos/tools
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 300; done;" ]
      securityContext:
        capabilities:
          add: [ "IPC_LOCK" ]
      resources:
        requests:
          nvidia.com/hostdev: '1'
        limits:
          nvidia.com/hostdev: '1'
