# Copyright 2020 NVIDIA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for network-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Maintenance Operator chart related values.
maintenance-operator-chart:
  operator:
    image:
      repository: ghcr.io/mellanox
      name: maintenance-operator
      tag: v0.2.0
    admissionController:
      # -- enable admission controller of the operator
      enable: false
      certificates:
        secretNames:
          # -- secret name containing certificates for the operator admission controller
          operator: "maintenance-webhook-cert"
        certManager:
          # -- use cert-manager for certificates
          enable: false
          # -- generate self-signed certificates with cert-manager
          generateSelfSigned: false
        custom:
          # -- enable custom certificates using secrets
          enable: false         

# General Operator related values
# The operator element allows to deploy network operator from an alternate location
operator:
  # -- Optional `resource requests and limits <https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/>`_
  # for the operator.
  # @notationType -- yaml
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi
  # -- Set additional tolerations for various Daemonsets deployed by the operator.
  # @notationType -- yaml
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
  # -- Configure node selector settings for the operator.
  nodeSelector: {}
  affinity:
    # -- Configure node affinity settings for the operator.
    # @notationType -- yaml
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values: [""]
        - weight: 1
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/control-plane"
                operator: In
                values: [ "" ]
  # -- Network Operator image repository.
  repository: harbor.mellanox.com/cloud-orchestration-dev/amaslennikov
  tag: latest
  # -- Network Operator image name
  image: network-operator
  # imagePullSecrets: []
  # -- Name to be used as part of objects name generation.
  nameOverride: ""
  # -- Name to be used to replace generated names.
  fullnameOverride: ""
  # tag, if defined will use the given image tag, else Chart. AppVersion will be used.
  # tag
  # -- Directory, where CNI binaries will be deployed on the nodes. Setting for 
  # the sriov-network-operator is set with ``sriov-network-operator.cniBinPath``
  # parameter. Note that the CNI bin directory should be aligned with the CNI bin
  # directory in the container runtime.
  cniBinDirectory: /opt/cni/bin
  # -- Enable the use of Driver ToolKit to compile DOCA Drivers (OpenShift only).
  useDTK: true
  admissionController:
    # -- Deploy with admission controller.
    enabled: false
    # -- Use cert-manager for generating self-signed certificate.
    useCertManager: true
    # certificate:
      # caCrt: |
      #   -----BEGIN CERTIFICATE-----
      #   MIIMIICLDCCAdKgAwIBAgIBADAKBggqhkjOPQQDAjB9MQswCQYDVQQGEwJCRTEPMA0G
      #   ...
      #   -----END CERTIFICATE-----    
      # tlsCrt: |
      #   -----BEGIN CERTIFICATE-----
      #   MIIMIICLDCCAdKgAwIBAgIBADAKBggqhkjOPQQDAjB9MQswCQYDVQQGEwJCRTEPMA0G
      #   ...
      #   -----END CERTIFICATE-----
      # tlsKey: |
      #   -----BEGIN EC PRIVATE KEY-----
      #   MHcl4wOuDwKQa+upc8GftXE2C//4mKANBC6It01gUaTIpo=
      #   ...
      #  -----END EC PRIVATE KEY-----
  ofedDriver:
    initContainer:
      # -- Deploy init container.
      enable: false
      # -- Init container image repository.
      repository: ghcr.io/mellanox
      # -- Init container image name.
      image: network-operator-init-container
      # -- Init container image version.
      version: v0.0.3

# -- An optional list of references to secrets to use for pulling any of the
# Network Operator images.
imagePullSecrets: []

# @ignore
test:
  pf: ens2f0
