# permissions for end users to view macvlannetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: macvlannetwork-viewer-role
rules:
- apiGroups:
  - mellanox.com
  resources:
  - macvlannetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mellanox.com
  resources:
  - macvlannetworks/status
  verbs:
  - get
