# permissions for end users to view nicclusterpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nicclusterpolicy-viewer-role
rules:
- apiGroups:
  - mellanox.com
  resources:
  - nicclusterpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mellanox.com
  resources:
  - nicclusterpolicies/status
  verbs:
  - get
