# permissions for end users to edit nicclusterpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nicclusterpolicy-editor-role
rules:
- apiGroups:
  - mellanox.com
  resources:
  - nicclusterpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mellanox.com
  resources:
  - nicclusterpolicies/status
  verbs:
  - get
