apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{.NetworkName}}
  namespace: {{.NetworkNamespace}}
spec:
  config: '{
  "cniVersion":"0.3.1",
  "name":"{{.NetworkName}}",
  "type":"ipoib",
  "master": "{{.Master}}",
  {{.Ipam}}
}'
